### ISSUE TITLE
MenuMenuItem

### ISSUE THREAD

**Issue by AydinHassan** [mikeymike/cli-menu#2]
I'm really digging the advanced example but It's pretty tricky to use, especially if I want to create each menu in a factory so I can inject services as callables. Anyway I was thinking you could have a sort of `MenuMenuItem` or an `addMenu` method. You would pass an instance of another `CliMenu` In that method you could call `setParent($this)` on the child menu, so it can switch back. Thoughts?

**Comment by mikeymike** [comment]
Done, for now there is however some changes I want to make which will be in the TODO issue
